### ISSUE TITLE
mis_builder - extend AccountingExpressionProcessor

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-financial-reporting#126]
Hello,

We need to extend the mis_builder to handle what we call 'Operating Units', a new concept explained here:
https://docs.google.com/document/d/1iF2tKqCGjpZhTABU4oBT62sM08JFuNBXOtChbOSyBXQ/edit?usp=sharing

And corresponding repo here:
https://github.com/Eficent/odoo-operating-unit

We intend to use Mis_builder to filter a P&L or Balance Sheet by one or more specific operating units.

The problem we're facing is that in order to do that we must change the method 'get_aml_domain_for_dates' of class 'AccountingExpressionProcessor'. But since class 'AccountingExpressionProcessor' derives from 'object' and not from models.AbstractModel, we cannot call super in this method, fetch the values and then extend it with additional domain content. We can only monkey patch this method.

Any ideas of how to overcome this  @sbidoul ?

**Comment by sbidoul** [comment]
We could make AEP and AbstractModel, but I think class is not really meant to be extended.

I wrote some thoughts about this in the README roadmap section: _A mechanism to have a global move line filter at the level of the report template, report instance, or even column. Such a domain filter would be ANDed with the other filters and would allow to easily create reports filtered on analytic axis or business unit. To be complete such a mechanism should allow implementing similar filters on non accounting queries._

With mis_builder as is, you can already write expressions such as `balp[60%][('operating_unit_id', '=', ...)]`. But you know that, since you did reports for projects.

What I'd suggest is start with the following:
- add an "Additional Domain" field on mis.report and mis.report.instance
- AND these two domains and pass the result as an additional parameter to `aep.do_queries()`
- append it here: https://github.com/OCA/account-financial-reporting/blob/9.0/mis_builder/models/aep.py#L349

Then it's just a matter of extending the `mis.report.instance` form in your operational unit module to add the OU field and update the new domains in the on-change.

I think it would be a good start and I'm totally willing to review such a PR.

**Comment by sbidoul** [comment]
@jbeficent please have a look at #128. This should provides the hooks you need.

**Comment by sbidoul** [comment]
This is now implemented. Closing.
