### ISSUE TITLE
[9.0 and 10.0] account_financial_report_qweb works as admin user, but not as regular user

### ISSUE THREAD

**Issue by wim-a** [OCA/account-financial-reporting#252]
I installed the module account_financial_report_qweb on Odoo 9.0 Enterprise Edition, and the reports work very well as admin user, but when I run them as normal user (f.e. with Adviser role), the reports only print titles and group headers (f.e. accounts), but all detail lines are not printed.

I have been looking to the module to try to figure out what the problem can be, but I couldn't find it. To try to verify what's going wrong, I replaced the transientmodels by normal models (and added a security group for them). By doing this, the reports work well.

The problem appears both in the pdf reports, and in the xlsx export.

**Comment by Sananaz** [comment]
Any update on this issue.

**Comment by mra-odoo** [comment]
Hello,

We have same issue while using module, Only admin can print and see results.

Please suggest solution for this.

Thanks in Advance

**Comment by alexis-via** [comment]
I am also impacted by this bug on odoo 10 community.

Steps to reproduce the problem:
1) install account_financial_report_qweb on an Odoo 10 with demo data
2) create a customer invoice and validate it
3) as "admin" user, go to "Accounting > OCA accounting reports > Aged partner balance", keep default options in the wizard and print as PDF or XLSX => you see at least one line corresponding to your invoice
4) logout and re-login as "demo" user. Again, go to "Accounting > OCA accounting reports > Aged partner balance", keep default options in the wizard and print as PDF or XLSX => the report doesn't work, there are no lines!

One thing to notice in the odoo server logs: as demo user, you have this msg in the logs:
```
2017-01-24 20:14:17,263 5790 INFO o0_test1 odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: write, uid: 5, model: ir.ui.view
```
This line is caused by the web_editor module, in particuliar this line of code: https://github.com/odoo/odoo/blob/10.0/addons/web_editor/models/ir_ui_view.py#L21
But, even you comment these lines, it still doesn't work.

**Comment by alexis-via** [comment]
@jcoux @yvaucher @simahawk If you have a clue or a direction about this bug, please tell us. I'd like to fix it, but I need some hints about this strange access-rights bug in account_financial_report_qweb.

**Comment by sbidoul** [comment]
I confirm the issue. As far as I can tell, it happens only with the aged partner balance.
The total amount is correct but no line is displayed when using any other login than admin.

**Comment by sbidoul** [comment]
I have no idea on the source of the error. The fact that the total is correct may be a hint for someone familiar with that code.

@jbeficent have you seen that too?

**Comment by alexis-via** [comment]
If you add an ACL with full rights on ir.ui.view for the Accountant group, you don't have the error message any more, but you still have the bug. So the error log line is probably unrelated.

**Comment by alexis-via** [comment]
If you look at the table report_aged_partner_balance_qweb_partner when the report is generated as demo user, you see that the data is generated fine. I think we have to investigate in the report inclusion (the qweb report is made of several qweb report templates included in the main qweb report).

**Comment by alexis-via** [comment]
I now focus my debug on the XLSX output, because it's easier to print data in the middle of the report generation.

If you print "partner.line_ids" at this line of code https://github.com/OCA/account-financial-reporting/blob/10.0/account_financial_report_qweb/report/aged_partner_balance_xlsx.py#L161
you have an empty value when run as demo user... although a "select * from report_aged_partner_balance_qweb_line order by id desc;" will should that a line has been created.

So the data exists in postgres, but not in the ORM...

**Comment by alexis-via** [comment]
All the data of the report is computed in SQL and then there is a call of self.refresh():
https://github.com/OCA/account-financial-reporting/blob/10.0/account_financial_report_qweb/report/aged_partner_balance.py#L229
which I guess is supposed to force the ORM to sync with the SQL...
I think the key of the problem is here...

**Comment by alexis-via** [comment]
Bug found and fixed. PR coming !

**Comment by alexis-via** [comment]
PR ready to review: https://github.com/OCA/account-financial-reporting/pull/265

**Comment by sbidoul** [comment]
This one is fixed.
