### ISSUE TITLE
[9.0][mis_report] Issues creating monthly periods

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-financial-reporting#279]
In 9.0 and 10.0 (#275) it is not straightforward to create a mis report that uses monthly periods.

The user has to choose the mode "Relateive to report base date", select the period type "Date Range" and date range type "Month". But then, how does the system know how to compute a month?

![image](https://cloud.githubusercontent.com/assets/7683926/24001534/ac3041f4-0a5e-11e7-9127-fae9734103ee.png)

It seems to me that month should be a period type, just like day or week.

Anyway, it is not clear how should one use the date range type.

**Comment by JordiBForgeFlow** [comment]
cc @sbidoul

**Comment by sbidoul** [comment]
The system does not actually *known* what a month is. However, if the user has previously created the date ranges corresponding to each month (possibly using the generator in the date_range module), it should just work as expected.

In your example, if From and To remain empty, it's probably because the corresponding date ranges do not exist yet.

If they do exist, then it's a bug.

In essence, it's not much different from v8 where you had to create the accounting period for this to work. Except that you had to create the periods anyway for accounting to work, so you would not forget.

**Comment by JordiBForgeFlow** [comment]
OK, I understand.
