### ISSUE TITLE
Customer Outstanding Statement Computing Error on Refunds

### ISSUE THREAD

**Issue by chynwey** [OCA/account-financial-reporting#300]
Aging bucket is not calculated correctly. Aging bucket total due does not sum up to the actual balance

Example as attached. 

[Statement Action to PDF-2.pdf](https://github.com/OCA/account-financial-reporting/files/949724/Statement.Action.to.PDF-2.pdf)

**Comment by MiquelRForgeFlow** [comment]
In your statement, you have an unclaimed refund. That means it's not reconciled. The Aging buckets in the beginning were designed to take into account just unpaid invoices because it's no common to have unclaimed refunds and outstanding payments.

But after a thought, I think you have a point. So, I made the PR https://github.com/OCA/account-financial-reporting/pull/301 to fix this.

**Comment by JordiBForgeFlow** [comment]
Fixed.
