### ISSUE TITLE
Proposal to hide journal selection in general ledger wizard

### ISSUE THREAD

**Issue by Danisan** [OCA/account-financial-reporting#486]
In account_financial_report_qweb, there is a selector for al journals, that by default is empty.

If you have your system plenty of journals, It is an annoyance for users to select all of them. Actually I don't find sense to have a selector for journals, since that way, there is no guarantee that there are no movements for the same selected accounts in the same selected date range in not chosen journals, and the information that you get is in some way, slanted.

My proposal is to hide the journals, and assume that you need all of them. If you agree I've the PR ready for v10.0.

The other thing is that several customers asked me to add and account range. So if you think this is also suitable I can PR that too.

**Comment by pedrobaeza** [comment]
-1 to first proposal. If you don't want to use journal selection, don't use it. Leave it empty will show everything.

About the other proposal, it's interesting, but you can get similar things with "Search more..." option + multi-select (web_widget_many2many_tags_multi_selection).

**Comment by fclementic2c** [comment]
I need this selector. we added it quite recently in fact.

The idea is to be able isolate closing entries since there is no special closing period to handle this.
It is also used for some specific analysis.

But I agree that this is not the most important feature and it could be in a separate tab or at the bottom...
