### ISSUE TITLE
[12.0] VAT Report amount incorrect for 0% VAT

### ISSUE THREAD

**Issue by microsound1** [OCA/account-financial-reporting#590]
Some 0% VAT vendor bill not including on VAT report.
Tax balance report displays correctly all amount.

**Comment by tm-up** [comment]
This happens because no move lines are generated if the tax amount is zero. Applies also to 11.0.
We fixed this by changing the test for tax amount == 0 in account_invoice.py, line 1031, "if tax_line.amount_total:" to "if 1:"

The problem also happens with 100% VAT bills from the government (EZV in Switzerland) or an import-company like Fedex.
