### ISSUE TITLE
VAT report issue regarding periods with purchase receipts

### ISSUE THREAD

**Issue by tm-up** [OCA/account-financial-reporting#610]
When using purchase receipts, one can enter a "Accounting Date" and a "Bill Date". If the two dates are not within the same reporting period, some reports will disagree on the amounts of tax:

The VAT report of OCA seems to use the "Accounting Date " (account_date) to calculate the VAT sums of a period. If you use filters to extract the data from the Purchase receipts grid, you get a different sum, apparently the "Bill Date" is used here.

We believe that the VAT report should use the "Bill Date" and NOT the "Accounting Date".
Looking into the code, we think that the problem lies in the account_voucher module, which uses the "Accounting Date" (account_date) for the tax move lines. So maybe this issue should be reported on odoo/odoo/addons...?

**Comment by JordiBForgeFlow** [comment]
Hi,

This is not correct. The accounting date is what must be used for VAT
reports.

The reason is simple. You might receive bills from vendor and not be able
to enter them or report them to the authorities within the period of the
bill date. Imagine, for example, that the bill was mailed to you
(physically) and you receive it 10 days after the reporting period was
finished.

That is why, for vendor bills, authorities allow you to report bills on a
date after the bill date (you might have a period limit, like a year).


When you create the VAT report it must reflect all the vendor bills that
you decide to recognize for that period.


How could you possibly be able to report a vendor bill on a reporting
period in the past, where you have submitted the totals? It would be so
confusing for the tax autorities to continuously receive amendments to
already submitted VAT statements, just because you forgot to enter or
received a vendor bill too late?


Hope that this clarifies the issue.


Regards,
Jordi

**Comment by pedrobaeza** [comment]
Yes, the explanation given by @jbeficent is correct, so closing this.
