### ISSUE TITLE
[12.0][partner_statement] Display the payment ref instead of 'Payment' string

### ISSUE THREAD

**Issue by kh-badep** [OCA/account-financial-reporting#633]
Hello,

When printing an activity statement it seems logical that the column Description is supposed to display additional information about the transaction, which can be:
- The invoice reference (account.move,name) if it's an invoice
- The transaction communication (account.payment,communication) if it's a payment, which can be the check number, etc.

However, that column seems to be filled with a generic 'Payment' string when it's a payment and upon inspecting code, it is forced here:
https://github.com/OCA/account-financial-reporting/blob/2953498afedcc60547aaaf851eda490e162bfef2/partner_statement/report/activity_statement.py#L66

Why not just use the columns `name` and `ref` as is instead of testing on the journal type. We can just drop the `CASE` statement so that the payment reference will be printed.

**Comment by gdgellatly** [comment]
Yes this was a deliberate decision. Hence why there was a special case created. To be honest I don't really remember the reason why now, but it was necessary at the time.

@metamasterplay I remember why now, it all looks fine when you have a single payment paying a single invoice. But when you have a single payment paying hundreds of invoices it is a complete messs.

**Comment by kh-badep** [comment]
Hello,
The only scenario I have found matching your description is when a user select multiple invoices from the tree view and then run the action `Register Payment` and then `Group Invoices`. And even then the user can choose to input a custom memo instead of the concatenated invoice numbers:
![image](https://user-images.githubusercontent.com/12763123/71580789-6ef99200-2b02-11ea-8938-efb5ba0e9c29.png)

Anyway since it's a stored string I guess it's a presentation issue rather than a performance one. Could we maybe truncate to a predefined character number in the report, or even use the `text-overflow` css property?

**Comment by gdgellatly** [comment]
@metamasterplay It is nothing to do with the string choice, we use the same string for grouping purposes. Otherwise a single payment, paying 100 invoices printed as 100 lines when reconciled through the bank statement interface or the reconciliation widget (because the process of paying created loads of seperate move lines, each with their own ref). Or at least it used to, there's actually been quite a lot of fixes to the SQL of this module since then, plus upstream changes. 

So maybe the original problem is fixed, maybe it isn't, but it needs to be proven first that you aren't breaking/regressing behaviour. This wasn't some spur of the moment thing, it was very deliberate and done with an entirely separate commit. https://github.com/OCA/account-financial-reporting/commit/aaa9c724210b4c0d26acec38ca94301ba0705ba8 - But it was done late on a tight deadline, so it was always kind of not quite right, but the alternative was worse

**Comment by kh-badep** [comment]
I was not able to reproduce this behavior. When using the bank statement reconciliation the payment ref always take the statement line ref. whether it's reconciling 1 or 100 invoices.

I'll close this issue since I'm not entirely sure what we're up against. For the time being this behavior can be emulated with a [custom module](https://github.com/BADEP/addons/tree/12.0/partner_statement_fix) for whoever needs it.
