### ISSUE TITLE
8.0 account_financial_report_webkit : Aged Partner Balance issue

### ISSUE THREAD

**Issue by loicbaechler** [OCA/account-financial-reporting#91]
I thing there is an issue when using aged partner balance report.
I can not print on a specific date.

When I select the periode of June and the 22th of June a warning message is displayed.
[Field(s) `until_date` failed against a constraint: Clearance date must be the very last date of the last period or later.] 
![image](https://cloud.githubusercontent.com/assets/8722390/8333339/b4a64de6-1a92-11e5-871f-66a3c2fcd9ea.png)

If I chose the month of May and the 22th of June, invoices of June are not displayed into the report.
![image](https://cloud.githubusercontent.com/assets/8722390/8333363/d0e33208-1a92-11e5-8345-edfc5efcf91f.png)

**Comment by loicbaechler** [comment]
News concerning this bug?

**Comment by sbidoul** [comment]
The previous wizard had usability issues.

The new one can only report at end of period indeed.

I agree it would be better to have a date selection instead of period selection. @fclementic2c do you agree too?

It may not be a trivial change, though. I've not investigated and unfortunately we (at ACSONE) have no ressources to dedicate to this issue at the moment. PR's are welcome.

**Comment by pedrobaeza** [comment]
Closing as this is old and seems to be a solution (limiting the wizard).
